<?php
/*
	Tenkana Jquery Mobile MVC ( TJM-MVC ) 1.0 (c) 2011, Nguyen Nhu Anh

	http://www.tenkana.vn/
	
	File: bootstrap.php
	Version: 1.0
	Description: 
	    - This file is loaded automatically by the index.php
		- Use this to set up database details and other stuff

	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.
	
	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

*/
define('VERSION', '1.0');

define('BASE_DIR', dirname(__FILE__).'/');
define('LIB_DIR', BASE_DIR.'lib/');
define('MODEL_DIR', BASE_DIR.'models/');
define('PAGE_DIR', BASE_DIR.'pages/');
define('THEME_DIR', BASE_DIR.'themes/');
define('PLUGIN_DIR', BASE_DIR.'plugin/');